#######################################################################################
# Book settings
title                       : The ISA cookbook  # The title of the book. Will be placed in the left navbar.
author                      : The ISA Team  # The author of the book
copyright                   : "2021 (CC-BY 4.0)"  # Copyright year to be placed in the footer
logo                        : "./_static/images/isa_footer_logo.svg"  # A path to the book logo
exclude_patterns            : []  # Patterns to skip when building the book. Can be glob-style (e.g. "*skip.ipynb")

#######################################################################################
# Execution settings
execute:
  execute_notebooks         : off  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  cache                     : ""  # A path to the jupyter cache that will be used to store execution artifacs. Defaults to `_build/.jupyter_cache/`
  exclude_patterns          : []  # A list of patterns to *skip* in execution (e.g. a notebook that takes a really long time)

#######################################################################################
# HTML-specific settings
html:
  favicon                   : "./_static/images/logo/isa.ico"  # A path to a favicon image
  navbar_number_sections    : True  # Add a number to each section in your left navbar
  use_edit_page_button      : True   # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button     : True  # Whether to add a link to your repository button
  use_issues_button         : True  # Whether to add an "open an issue" button
  extra_navbar              : Powered by <a href="https://jupyterbook.org">Jupyter Book</a>  # Will be displayed underneath the left navbar.
  extra_footer              :   # Will be displayed underneath the footer.
    <script>mermaid.init();</script>
    <div class="row_footer">
    This page was created thanks to work by <a href="https://github.com/jupyter/jupyter-book/graphs/contributors">The Jupyter Book Community</a></div>
    <div class="row_footer">
    This project is supported financially by the <a href="https://wellcome.org/">Welcome Trust</a>, Elixir-UK and the European Union</div>

    <div class="row_footer">
    <div class="column" style="center"><a href="https://wellcome.org/"><img src="../_static/images/logo/wellcome-logo-black.png" height="25" alt="Wellcome" style="float:center""></a></div>
    <div class="column"><a href="https://www.elixir-uk.org.eu/"><img src="../_static/images/logo/elixir-uk_transparent.png" height="40" alt="IMI logo" style="float:center""></a></div>
    <div class="column"><a href="https://https://ec.europa.eu/programmes/horizon2020/en"><img src="../_static/images/logo/eu-flag-recolored.png" height="25" alt="EFPIA logo" style="float:center""></a></div>
    </div>

  google_analytics_id       : ""  # A GA id that can be used to track book views.
  home_page_in_navbar       : true  # Whether to include your home page in the left Navigation Bar
  baseurl                   : "https://isa-tools.github.io/isa-api"  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/

  comments:
    hypothesis: true
    utterances:
      repo: "isa-tools/isa-api"

#######################################################################################
# Launch button settings
launch_buttons:
  notebook_interface        : "jupyterlab" # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url             : "https://mybinder.org"  # The URL of the BinderHub (e.g., https://mybinder.org)
  jupyterhub_url            : ""  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)
  thebelab                  : false  # Add a thebelab button to pages (requires the repository to run on Binder)
  colab_url                 : "https://colab.research.google.com"

repository:
  url                       : https://github.com/isa-tools/isa-api  # The URL to your book's repository
  path_to_book              : "isa-cookbook"  # A path to your book's folder, relative to the repository root.
  branch                    : master  # Which branch of the repository should be used when creating links

#######################################################################################
# Advanced and power-user settings
sphinx:
  extra_extensions          :   # A list of extra extensions to load by Sphinx.
   # - sphinx_tabs.tabs
  config                    :   # key-value pairs to directly over-ride the Sphinx configuration
