__author__ = 'dj'

import datetime

class Investigation(object):
    """An investigation maintains metadata about the project context and links to one or
    more studies. Investigations has the following properties:

    Attributes:
        identifier: A locally unique identifier or an accession number provided by a repository.
        title: A concise name given to the investigation
        description: A textual description of the investigation
        submissionDate: The date on which the investigation was reported to the repository.
        publicReleaseDate: The date on which the investigation should be released publicly
        ontologySourceReferences: This annotation section is identical to that in the MAGE-TAB format.
        publications: Publications associated with an Investigation.
        contacts: People/contacts associated with an Investigation.
        studies: Study is the central unit, containing information on the subject under study, its characteristics and
        any treatments applied.
    """

    def __init__(self):
        """Return an empty Investigation object with default set to empty values."""
        self.identifier = ""
        self.title = ""
        self.description = ""
        self.submissionDate = datetime.date
        self.publicReleaseDate = datetime.date
        self.ontologySourceReferences = []
        self.publications = []
        self.contacts = []
        self.studies = []


class OntologySourceReference(object):
    """This annotation section is identical to that in the MAGE-TAB format.

    Attributes:
        name: The name of the source of a term; i.e. the source controlled vocabulary or ontology.
        file: A file name or a URI of an official resource.
        version: The version number of the Term Source to support terms tracking.
        description: Use for disambiguating resources when homologous prefixes have been used.
    """

    def __init__(self):
        """Returns an empty OntologySourceReference object with default set to empty values"""
        self.name = ""
        self.file = ""
        self.version = ""
        self.description = ""

class OntologyAnnotation(object):
    """An ontology term annotation reference

    Attributes:
        termSource: The abbreviated ontology name. It should correspond to one of the sources as specified in the
        ontologySourceReference section of the Investigation.
        termAccession: URI
    """


class Publication(object):
    """A publication associated with an investigation or study.

    Attributes:
        pubMedID: The PubMed IDs of the described publication(s) associated with this investigation.
        DOI: A Digital Object Identifier (DOI) for that publication (where available).
        authorList: The list of authors associated with that publication.
        title: The title of publication associated with the investigation.
        status: A term describing the status of that publication (i.e. submitted, in preparation, published).
    """

    def __init__(self):
        """Return an empty Publication object with default set to empty"""
        self.pubMedID = ""
        self.DOI = ""
        self.authorList = ""
        self.title = ""
        self.status = ""


class Person(object):
    """A person/contact that can be attributed to an Investigation or Study.

    Attributes:
        lastName: The last name of a person associated with the investigation.
        firstName: The first name of a person associated with the investigation.
        midInitials: The middle initials of a person associated with the investigation.
        email: The email address of a person associated with the investigation.
        phone: The telephone number of a person associated with the investigation.
        fax: The fax number of a person associated with the investigation.
        address: The address of a person associated with the investigation.
        affiliation: The organization affiliation for a person associated with the investigation.
        roles: Term to classify the role(s) performed by this person in the context of the investigation,
        which means that the roles reported here need not correspond to roles held withing their
        affiliated organization.
    """

    def __init__(self):
        """Return an empty Person object with default set to empty"""
        self.lastName = ""
        self.firstName = ""
        self.midInitials = ""
        self.email = ""
        self.phone = ""
        self.fax = ""
        self.address = ""
        self.affiliation = []
        self.roles = []


class Study(object):
    """Study is the central unit, containing information on the subject under study, its characteristics
    and any treatments applied.

    Attributes:
        identifier: A unique identifier: either a temporary identifier supplied by users or one generated by a
        repository or other database.
        title: A concise phrase used to encapsulate the purpose and goal of the study.
        description: A textual description of the study, with components such as objective or goals.
        submissionDate: The date on which the study is submitted to an archive.
        publicReleaseDate: The date on which the study should be released publicly.
        fileName: A field to specify the name of the Study file corresponding the definition of that Study.
        designDescriptors: Classifications of the study based on the overall experimental design.
        publications: Publications associated with a Study.
        contacts: People/contacts associated with a Study.
        factors: A factor corresponds to an independent variable manipulated by the experimentalist with the intention
        to affect biological systems in a way that can be measured by an assay.
        protocols: Protocols used within the ISA artifact.
        assays: An Assay represents a portion of the experimental design.
    """

    def __init__(self):
        """Return an empty Study object with default set to empty"""
        self.identifier = ""
        self.title = ""
        self.description = ""
        self.submissionDate = datetime.date
        self.publicReleaseDate = datetime.date
        self.fileName = ""
        self.designDescriptors = []
        self.publications = []
        self.contacts = []
        self.factors = []
        self.protocols = []
        self.assays = []

class StudyDesignDescriptor(object):
    """A Study Design Descriptor provides a term allowing the classification of the study based on the overall
    experimental design. The term can be free text (Attribute: name) or from, for example, a controlled vocabulary or
    an ontology (Attribute: ontologyReference).

    Attributes:
        name: Free text name for the term
        ontologyAnnotation: A representation of an ontology annotation
    """

    def __init__(self):
        self.name = ""
        self.ontologyAnnotation = OntologyAnnotation()

class StudyFactor(object):
    """A Study Factor corresponds to an independent variable manipulated by the experimentalist with the intention to
    affect biological systems in a way that can be measured by an assay.

    Attributes:
        name: Free text name for the term
        ontologyReference: A representation of an ontology source reference
    """

    def __init__(self):
        self.name = ""
        self.ontologyAnnotation = OntologyAnnotation()

class Assay(object):
    """A Study Assay declares and describes each of the Assay files associated with the current Study.

    Attributes:
    Measurement Type: A term to qualify the endpoint, or what is being measured (e.g. gene expression profiling or protein
identification). The term can be free text or from, for example, a controlled vocabulary or an ontology.
    Technology Type: Term to identify the technology used to perform the measurement, e.g. DNA microarray, mass
spectrometry. The term can be free text or from, for example, a controlled vocabulary or an ontology.
    Technology Platform: Manufacturer and platform name, e.g. Bruker AVANCE
    File Name: A field to specify the name of the Assay file corresponding the definition of that assay.
    """
    def __init__(self):
        self.measurementType = OntologyAnnotation()
        self.technologyType = OntologyAnnotation()
        self.fileName = ""
