from isatools.database.models.comment import Comment
from isatools.database.models.investigation import Investigation
from isatools.database.models.ontology_source import OntologySource
from isatools.database.models.ontology_annotation import OntologyAnnotation
from isatools.database.models.parameter import Parameter
from isatools.database.models.person import Person
from isatools.database.models.process import Process
from isatools.database.models.protocol import Protocol
from isatools.database.models.publication import Publication
from isatools.database.models.study import Study
